logging:
  level:
    root: info
    org.hiberante.SQL: debug
    org.hiberante.type: trace

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100

    hibernate:
      ddl-auto: create

  profiles:
    active: local, jwt

  kafka:
#    consumer:
#      bootstrap-servers: ec2-3-34-190-54.ap-northeast-2.compute.amazonaws.com:9092
#      group-id: foo
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: ec2-3-34-190-54.ap-northeast-2.compute.amazonaws.com:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

